'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { RequestsCenter } from './requests-center';
import { useRealtimeNotifications, RealtimeNotification } from './use-realtime-notifications';

type Workspace = { user: { name: string; email: string }; tenant: { name: string }; membership: { role: string }; subscription: { plan: string; status: string } | null };
type Notification = RealtimeNotification & { id: string; createdAt: string; readAt: string | null };
const nav = [ ['Overview','◈'],['Rooms','▦'],['Guests','◎'],['Reservations','□'],['Requests','↗'],['Staff','◇'],['Finance','$'],['Settings','⚙'] ];
const demoMetrics = [['Occupancy','82.4%','+5.7%'],['Revenue','$428,650','+12.8%'],['Reservations','486','+8.4%'],['Open requests','07','-18.2%']];
const demoBars = [38,54,47,66,58,72,64,81,69,88,76,94,84,91];

export default function Home() {
  const [active,setActive]=useState('Overview');
  const [workspace,setWorkspace]=useState<Workspace|null>(null);
  const [notifications,setNotifications]=useState<Notification[]>([]);
  const [showNotifications,setShowNotifications]=useState(false);
  const [livePulse,setLivePulse]=useState(false);
  const base=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';
  useEffect(()=>{ fetch(`${base}/auth/me`,{credentials:'include'}).then(r=>r.ok?r.json():null).then(d=>d&&setWorkspace(d)).catch(()=>undefined); fetch(`${base}/notifications/unread`,{credentials:'include'}).then(r=>r.ok?r.json():[]).then(d=>Array.isArray(d)&&setNotifications(d)).catch(()=>undefined); },[base]);
  const onRealtime=useCallback((event:RealtimeNotification)=>{ if(!event.id)return; const n={...event,id:event.id,createdAt:event.createdAt??new Date().toISOString(),readAt:null}; setNotifications(c=>[n,...c.filter(x=>x.id!==n.id)].slice(0,50)); setLivePulse(true); window.setTimeout(()=>setLivePulse(false),1400); },[]);
  useRealtimeNotifications(onRealtime);
  const markRead=async(id:string)=>{const r=await fetch(`${base}/notifications/${id}/read`,{method:'PATCH',credentials:'include'});if(r.ok)setNotifications(c=>c.filter(n=>n.id!==id));};
  const name=workspace?.user.name??'Workspace', hotel=workspace?.tenant.name??'Your hotel', role=workspace?.membership.role??'DEMO', plan=workspace?.subscription?.plan??'DEMO';
  const greeting=useMemo(()=>{const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening';},[]);
  return <main className="workspace">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">V</span><span>VANTARA</span><small>HOTEL OPERATING SYSTEM</small></div><div className="hotel-card"><div className="eyebrow">Active property</div><div className="hotel-name">{hotel}</div><div className="hotel-meta"><span className="signal-dot"/>{plan} · {workspace?.subscription?.status??'PREVIEW'}</div></div><nav className="nav"><div className="nav-label">Workspace</div>{nav.map(([label,glyph])=><button key={label} className={active===label?'active':''} onClick={()=>setActive(label)}><span className="nav-glyph">{glyph}</span>{label}{label==='Requests'&&<span className="nav-count">LIVE</span>}</button>)}</nav><div className="sidebar-footer"><div className="system-line"><span className="signal-dot"/> SYSTEM ONLINE</div><div className="user"><div className="avatar">{name.slice(0,1).toUpperCase()}</div><div><strong>{name}</strong><span>{role}</span></div></div></div></aside>
    <section className="main"><header className="topbar"><div><div className="breadcrumb">VANTARA / {active.toUpperCase()}</div><h1>{greeting}, {name.split(' ')[0]}.</h1><p>One operational view of {hotel}.</p></div><div className="topbar-actions"><div className="environment"><span/> DEMO ENVIRONMENT</div><button className={`notification-button ${livePulse?'live-pulse':''}`} onClick={()=>setShowNotifications(!showNotifications)} aria-label="Notifications">◌{notifications.length>0&&<b>{notifications.length}</b>}</button>{showNotifications&&<div className="notification-popover"><div className="popover-head"><strong>Notifications</strong><span>{notifications.length} unread</span></div>{notifications.length===0?<div className="empty-notifications">No unread notifications.</div>:notifications.slice(0,5).map(n=><button className={`notification-item ${n.severity.toLowerCase()}`} key={n.id} onClick={()=>markRead(n.id)}><span className="notification-pulse"/><div><strong>{n.title}</strong><p>{n.message}</p></div></button>)}</div>}</div></header>
    {active==='Requests'?<RequestsCenter/>:<Overview/>}</section>
  </main>;
}

function Overview(){return <><div className="preview-banner"><span className="preview-icon">◈</span><div><strong>Workspace preview</strong><span>Operational metrics below are demonstration data. Vantara will replace them with source-of-truth hotel data as modules go live.</span></div></div><section className="metrics" aria-label="Hotel performance preview">{demoMetrics.map(([label,value,change])=><div className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>{change} vs previous period</small></div>)}</section><section className="grid"><div className="panel chart-panel"><div className="panel-head"><div><span className="panel-kicker">Performance</span><h2>Revenue & occupancy</h2></div><span className="panel-meta">14 day preview · MXN</span></div><div className="chart">{demoBars.map((height,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:`${height}%`}}/></div>)}</div><div className="chart-axis"><span>14 days ago</span><span>Today</span></div></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">Today</span><h2>Hotel pulse</h2></div><span className="live-label"><i/> REALTIME</span></div><Pulse label="Check-ins" detail="Expected arrivals" value="24"/><Pulse label="Check-outs" detail="Departures" value="17"/><Pulse label="Rooms cleaning" detail="Housekeeping queue" value="08"/><Pulse label="Open requests" detail="Guest operations" value="07"/></div></section><section className="grid lower"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">Guest communication</span><h2>Recent requests</h2></div><span className="text-button">Open queue ↗</span></div><Request title="Extra towels · Room 407" detail="Housekeeping · 4 min ago" status="OPEN"/><Request title="AC inspection · Room 214" detail="Maintenance · 11 min ago" status="ASSIGNED"/><Request title="Room service · Room 508" detail="Food & beverage · 18 min ago" status="IN PROGRESS"/></div><div className="panel intelligence"><div className="intel-orbit"><span/><span/><span/></div><span className="panel-kicker">VANTARA INTELLIGENCE</span><h2>Built to understand the hotel.</h2><p>When real operating data is connected, this layer will turn reservations, rooms, requests and guest communication into actionable operational context.</p><div className="intel-footer">SOURCE OF TRUTH <span>CONNECTED LATER</span></div></div></section></>}
function Pulse({label,detail,value}:{label:string;detail:string;value:string}){return <div className="pulse"><div><strong>{label}</strong><span>{detail}</span></div><b>{value}</b></div>}
function Request({title,detail,status}:{title:string;detail:string;status:string}){return <div className="request"><div><strong>{title}</strong><span>{detail}</span></div><b>{status}</b></div>}
